name: Sloth Action

on: [push]

jobs:
  generate:
    name: Generate Sloth Output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Sloth Output
        uses: ./.github/actions/sloth
        with:
          input-file: ./veilarbaktivitet.yml
          output-file: output.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./output.yaml
