name: Sloth Action

on: [push]

jobs:
  generate:
    name: Generate Sloth Output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Sloth
        run: |
          wget https://github.com/slok/sloth/releases/download/v0.11.0/sloth-linux-amd64
          chmod +x sloth-linux-amd64

      - name: Generate Output
        run: ./sloth-linux-amd64 generate -i veilarbaktivitet.yml -o output.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./output.yaml
